config/routes.rb
TunrApp::Application.routes.draw do

  devise_for :users

  resources :musicians
  resources :bands
  resources :band_memberships

  root :to => 'bands#index'

  get '/' => 'bands#index'

  post '/bands/:id' => 'bands#update'

  post '/musicians/:id' => 'musicians#update'

end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :band_memberships
  has_many :musicians, through: :band_memberships
  attr_accessible :name

  
  def self.invent_name 
    Faker::Name.first_name + " and the "+ Faker::Commerce.product_name
  end


end

app/models/band_membership.rb
class BandMembership < ActiveRecord::Base
  belongs_to :band
  belongs_to :musician

  attr_accessible :band_id, :instrument, :musician_id, :band, :musician

end

app/models/musician.rb
class Musician < ActiveRecord::Base
  has_many :band_memberships
  has_many :bands, through: :band_memberships

  attr_accessible :name

  def join(band, instrument)
    BandMembership.create(
      instrument: instrument,
      band: band,
      musician: self
      )
  end


  def self.invent_name 
    Faker::Name.first_name + Faker::Name.first_name
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/band_memberships_controller.rb
class BandMembershipsController < ApplicationController

#     band_memberships GET    /band_memberships(.:format)          band_memberships#index
  def index
  end

#                      POST   /band_memberships(.:format)          band_memberships#create
  def create
    BandMembership.create(
      musician_id: params[:musician_id], 
      band_id: params[:band_id],
      instrument: params[:instrument],
      )
    redirect_to bands_path
  end

#  new_band_membership GET    /band_memberships/new(.:format)      band_memberships#new
  def new
    @musicians = Musician.all
    @bands = Band.all
  end

# edit_band_membership GET    /band_memberships/:id/edit(.:format) band_memberships#edit
#      band_membership GET    /band_memberships/:id(.:format)      band_memberships#show
#                      PUT    /band_memberships/:id(.:format)      band_memberships#update
#                      DELETE /band_memberships/:id(.:format)      band_memberships#destroy

 
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

#         bands GET    /bands(.:format)              bands#index
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @bands = Band.all
  end  

#               POST   /bands(.:format)              bands#create
  def create
    Band.create(name: params[:name])
    redirect_to bands_path
  end

#      new_band GET    /bands/new(.:format)          bands#new
  def new
  
  end

#     edit_band GET    /bands/:id/edit(.:format)     bands#edit
  def edit
    @band = Band.find(params[:id])
  end

#          band GET    /bands/:id(.:format)          bands#show
  def show
    @band = Band.find(params[:id])
  end

#               PUT    /bands/:id(.:format)          bands#update
  def update
    band = Band.find(params[:id])
    band.name = params[:band_name]
    band.save
    redirect_to band_path(band)
  end

#               DELETE /bands/:id(.:format)          bands#destroy
  def destroy
    Band.delete(params[:id])
    redirect_to bands_path
  end

### FORM HELPERS OPTION
  # def new
  #   @band = Band.new
  # end
  
  # def create
  #   Band.create(name: params[:band][:name])
  #   redirect_to bands_path
  # end

      ### FORM HELPER HTML
        # <%= form_for @band do |f| %>
        #  <%= f. text_field :name, placeholder: "new band" %> 
        #  <%= f.submit %> 
        # <% end %> 
###--

end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController

 #     musicians GET    /musicians(.:format)                 musicians#index
  def index
    @musicians = Musician.all
  end

 #               POST   /musicians(.:format)                 musicians#create
  def create
    @name = params[:name]
    Musician.create({name: @name})
    redirect_to musicians_path
  end

 #  new_musician GET    /musicians/new(.:format)             musicians#new
  def new
  
  end

 # edit_musician GET    /musicians/:id/edit(.:format)        musicians#edit
 def edit
    @musician = Musician.find(params[:id])
  end

 #      musician GET    /musicians/:id(.:format)             musicians#show
  def show
    @musician = Musician.find(params[:id])
  end

 #               PUT    /musicians/:id(.:format)             musicians#update
  def update
    musician = Musician.find(params[:id])
    musician.name = params[:musician_name]
    musician.save
    redirect_to musician_path(musician)
  end
 
 #               DELETE /musicians/:id(.:format)             musicians#destroy
  def destroy
    Musician.delete(params[:id])
    redirect_to musicians_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/band_memberships/new.html.erb
<form action="<%= band_memberships_path %>" method="post">
  <div class="row">
    <div class="col-lg-7">
      <select class="form-control input-lg" name="musician_id" >
        <% @musicians.each do |musician| %> 
          <option value="<%=musician.id%>"><%= musician.name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-7">
    <select class="form-control input-lg" name="band_id" >
      <% @bands.each do |band| %> 
        <option value="<%=band.id %>"><%= band.name %></option>
      <% end %>
    </select>
    </div>
  </div>
  <input class="form-control" id="focusedInput" type="text" name="instrument" placeholder="What instrument do they play?">
  <button type="submit" class="btn btn-default btn-lg" id="submit">
    Create Band Membership!
  </button>
</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>
<form action="/bands/<%=@band.id %>" method="post">
  <input class="form-control" id="focusedInput" type="text" name="band_name" value="<%= @band.name %>">
  <button type="submit" class="btn btn-default btn-lg" id="submit">
    Update Band!
  </button>
</form>

app/views/bands/index.html.erb
<h1>My Music</h1>
<table class="table table-hover">
  <% @bands.each do |band| %>
  <tr class="band_<%=band.id%>">
    <td class="name">
      <a href="<%= band_path(band)%>"><%= band.name %></a>
    </td>
    <td>
      <a href="<%= edit_band_path(band) %>">&#9998;</a></td>
    <td>
      <form action="<%= band_path(band) %>" method="post">
        <input type="hidden" value="delete" name="_method">
        <button class="delete btn-link" id="delete">&#10007;</button>
      </form>
    </td>
  </tr>
  <% end %>
</table>

app/views/bands/new.html.erb
<form action="/bands" method="post">
  <input class="form-control" id="focusedInput" type="text" name="name" placeholder="new band">
  <button type="submit" class="btn btn-default btn-lg" id="submit">
    Add Band!
  </button>
</form>

app/views/bands/show.html.erb
<h1>Band Page: <%= @band.name %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <td>Musician</td>
      <td>Instrument</td>  
    </tr>
  </thead>
  <tbody>
  <% @band.musicians.each do |musician| %>
    <tr>
      <td>
        <a href="<%= musician_path(musician) %>">
          <%= musician.name %>
        </a>
      </td>
      <td>
        <%= BandMembership.where(musician_id: musician.id, band_id: @band.id).first.instrument %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TunrApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="container">
    <a class="btn btn-default btn-lg" href="<%= bands_path %>">Home</a>
    <a class="btn btn-default btn-lg" href="<%= musicians_path %>">Musicians</a>
    <a class="btn btn-default btn-lg" href="<%= new_band_path %>">New Band</a>
    <a class="btn btn-default btn-lg" href="<%= new_musician_path %>">New Musician</a>
    <a class="btn btn-default btn-lg"href="<%= new_band_membership_path %>">New Bandmembership</a>
   
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  
    <% if user_signed_in? %>
      <p>Welcome <%= current_user.email %> </p>
      <%= link_to "Log Out", destroy_user_session_path, method: destroy %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
      
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/musicians/edit.html.erb
<h1>Edit Musician</h1>
<form action="/musicians/<%=@musician.id %>" method="post">
  <input class="form-control" id="focusedInput" type="text" name="musician_name" value="<%= @musician.name %>">
  <button type="submit" class="btn btn-default btn-lg" id="submit">
    Update Musician!
  </button>
</form>

app/views/musicians/index.html.erb
<h1>Musicians</h1>

<table class="table table-hover">
  <% @musicians.each do |musician| %>
  <tr class="musician_<%=musician.id%>">
    <td class="name">
      <a href="<%= musician_path(musician) %>">
        <%= musician.name %>
      </a>
    </td>
    <td>
      <form action="<%= musician_path(musician) %>" method="post">
        <input type="hidden" value="delete" name="_method">
        <button class="delete btn-link" id="delete">&#10007;</button>
      </form>
    </td>
  </tr>
  <% end %>
</table>

app/views/musicians/new.html.erb
<form action="/musicians" method="post">
  <input class="form-control" id="focusedInput" type="text" name="name" placeholder="new musician">
  <button type="submit" class="btn btn-default btn-lg" id="submit">
    Add Musician!
  </button>
</form>

app/views/musicians/show.html.erb
<h1>Musician: <%= @musician.name %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <td>Band</td>
      <td>Instrument Played</td>
      <td>Delete Membership</td>
    </tr>
  </thead>

  <tbody>
    <% @musician.bands.each do |band| %>
    <tr>
      <td class="name">
        <a href="<%= band_path(band) %>">
          <%= band.name %>
        </a>
      </td>
      <td>
        <%= BandMembership.where(musician_id: @musician.id, band_id: band.id).first.instrument %>
      </td>  
      <td>
        <form action="<%= musician_path(@musician) %>" method="post">
          <input type="hidden" value="delete" name="_method">
          <button class="delete btn-link" id="delete">&#10007;</button>
        </form>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>